name: E-Mail Release Notification
on:
  release:
    types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify about a new release
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: rebeca.cruz@before.com.br,becatriz7@gmail.com
        from: becatriz7@gmail.com
        secure: true
        body: |
            Release para HOMOLOGAÇÂO!
            https://github.com/becatriz/monorepo/releases/tag/1.10
        cc: becatrizlopes@gmail.com
        reply_to: becatriz7@gmail.com
        in_reply_to: becatriz7@gmail.com
        ignore_cert: true
        convert_markdown: true
        attachments: attachments.zip,git.diff,./dist/static/*.js
        priority: low
