name: Build & Deploy (Production)

on: 
  push:
    branches:
      - master
    paths: 
      - 'packages/server/**'

jobs:
  deploy:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout
      uses: actions/checkout@v2

      - name: Setup Node.js
      uses: actions/setup-node@v1
      witch: 
        node-version: 12.x

      - name: Deploy
        run: echo "Deploy"
